const APP_ROUTE = {
  MAIN_TAB: 'MAIN_TAB',
};

const HOME_ROUTE = {
  ROOT: 'HOME_ROOT',
  HOME: 'HOME',
  HOME_USER_LIST: 'HOME_USER_LIST',
};

const ACCOUNT_ROUTE = {
  ROOT: 'ACCOUNT_ROUTE',
};

// rendering bottom tabs
const TAB_NAVIGATION_ROOT = {
  HOME_ROUTE,
  ACCOUNT_ROUTE,
};

export { APP_ROUTE, ACCOUNT_ROUTE, TAB_NAVIGATION_ROOT };
